# permissions for end users to view databasesecretenginestaticroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: databasesecretenginestaticrole-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vault-config-operator
    app.kubernetes.io/part-of: vault-config-operator
    app.kubernetes.io/managed-by: kustomize
  name: databasesecretenginestaticrole-viewer-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - databasesecretenginestaticroles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - databasesecretenginestaticroles/status
  verbs:
  - get
