apiVersion: redhatcop.redhat.io/v1alpha1
kind: DatabaseSecretEngineStaticRole
metadata:
  labels:
    app.kubernetes.io/name: databasesecretenginestaticrole
    app.kubernetes.io/instance: databasesecretenginestaticrole-sample
    app.kubernetes.io/part-of: vault-config-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: vault-config-operator
  name: databasesecretenginestaticrole-sample
spec:
  authentication:
    path: kubernetes
    role: database-engine-admin
  path: test-vault-config-operator/database
  username: db-user
  rotationPeriod: 24h
  dBName: db-name
  rotationStatements:
    - ALTER ROLE "{{name}}" WITH PASSWORD '{{password}}';
